### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by stevenbarragan** [creationix/haml-js#83]
Does somebody has any idea about what could be causing this error?
```
TypeError: undefined is not a function
    at Function.eval (eval at <anonymous> (/Users/steven/workspace/gopro/ci-template-editor/editor-screen/node_modules/gulp-haml/node_modules/haml/lib/haml.js:595:29), <anonymous>:27:17)
    at Function.<anonymous> (/Users/steven/workspace/gopro/ci-template-editor/editor-screen/node_modules/gulp-haml/node_modules/haml/lib/haml.js:595:11)
    at execute (/Users/steven/workspace/gopro/ci-template-editor/editor-screen/node_modules/gulp-haml/node_modules/haml/lib/haml.js:602:8)
    at Function.render (/Users/steven/workspace/gopro/ci-template-editor/editor-screen/node_modules/gulp-haml/node_modules/haml/lib/haml.js:587:12)
    at hamlStream (/Users/steven/workspace/gopro/ci-template-editor/editor-screen/node_modules/gulp-haml/index.js:15:21)
    at wrappedMapper (/Users/steven/workspace/gopro/ci-template-editor/editor-screen/node_modules/gulp-haml/node_modules/map-stream/index.js:84:19)
    at Stream.stream.write (/Users/steven/workspace/gopro/ci-template-editor/editor-screen/node_modules/gulp-haml/node_modules/map-stream/index.js:96:21)
    at write (/Users/steven/workspace/gopro/ci-template-editor/editor-screen/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:605:24)
    at flow (/Users/steven/workspace/gopro/ci-template-editor/editor-screen/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:614:7)
    at Transform.pipeOnReadable (/Users/steven/workspace/gopro/ci-template-editor/editor-screen/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:646:5)
```

**Comment by ypresto** [comment]
I really want to use single quote because haml-lint gem, which uses rubocop syntax checker, warns about it.

```
RuboCop: Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols.
```

**Comment by Juanmcuello** [comment]
Same problem here using single quotes. Using double quotes fixes the issue, but that's not an option for me.

**Comment by soyuka** [comment]
Same issue here,

after investigation (I'm using [gulp-haml](https://github.com/stevelacy/gulp-haml)), when `render` is called, `escaperName` is `undefined`.

A quick fix is to add `escaperName = "html_escape";` in the [render function](https://github.com/creationix/haml-js/blob/master/lib/haml.js#L632).

**Comment by ypresto** [comment]
@soyuka 

Ahh, I understand. This library seems to support only JSON in attributes.

https://github.com/creationix/haml-js/blob/master/lib/haml.js#L27

I think automatically replacing `'` to `"` (of course `"`s inside of it too) if possible will be better for performance. Then skip `parse_interpol`.

**Comment by ypresto** [comment]
Just adding single quote test doesn't cause the exception (still not optimized js is generated).
It might be issue on gulp side.

**Comment by ypresto** [comment]
This project seems to be discontinued, isn't it? @aaronblohowiak
